/* expr
* Parses strings in the language generated by the rule:
* <expr> -> <term> { (+ | -) <term>}
*/
void expr()
{
	printf("Enter <expr>\n");
	/* Parse the first term */
	term();

	/* As long as the next token is + or -, get
	   the next token and parse the next term */
	while (nextToken == ADD_OP || nextToken == SUB_OP)
	{
		lex();
		term();
	}
	printf("Exit <expr>\n");
}