/* factor
* Parses strings in the language generated by the rule:
* <factor> -> id | int_constant | ( <expr> )
*/
void factor()
{
	printf("Enter <factor>\n");
	/* Determine which RHS */
	if (nextToken == IDENT || nextToken == INT_LIT)
		/* Get the next token */
		lex();
	else {
		if (nextToken == LEFT_PAREN)
		{
			lex();
			expr();
			if (nextToken == RIGHT_PAREN)
				lex();
			else
				printf("Error 1");
		}
		/* It was not an id, an integer literal, or a left
		parentheses */
		else printf("Error 2");
	}
	printf("Exit <factor>\n");
}