/* term
   Parses strings in the language generated by the rules:
   <term> -> <factor> {(* | /) <factor>}
*/
void term()
{
	printf("Enter <term>\n");
	/* Parse the first factor */
	factor();
	/* As long as the next token is * or /, get the
	* next token and parse the next factor */
	while (nextToken == MULT_OP || nextToken == DIV_OP)
	{
		lex();
		factor();
	}
	printf("Exit <term>\n");
}